version: '3.8'  # versiya qo'shing, agar yo'q bo'lsa
services:
  educenter-crm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educenter-crm
    restart: on-failure
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - '3001:3000'

  mongo:
    image: mongo
    container_name: mongo-new
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_user
      MONGO_INITDB_ROOT_PASSWORD: dev_pass
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"