export const EDUCATION_SOURCE = 'EDUCATION_SOURCE';

export const MODELS = {
  COURSES: 'COURSES_MODEL',
  GROUPS: 'GROUPS_MODEL',
  STUDENTS: 'STUDENTS_MODEL',
  TEACHERS: 'TEACHERS_MODEL',
  TIMETABLE: 'TIMETABLE_MODEL',
  GRADES: 'GRADES_MODEL',
  PAYMENTS: 'PAYMENTS_MODEL',
};
