export const EDUCATION_SOURCE = 'EDUCATION_SOURCE';
export const CACHE_MANAGER = 'CACHE_MANAGER';

export const MODELS = {
  COURSES: 'COURSES_MODEL',
  GROUPS: 'GROUPS_MODEL',
  STUDENTS: 'STUDENTS_MODEL',
  TEACHERS: 'TEACHERS_MODEL',
  TIMETABLE: 'TIMETABLE_MODEL',
};
